### PR TITLE
fix: let's use connection driver

### PR DESCRIPTION
**Pull request by git-avc**

### CODE REVIEW

**Comment by nextchamp-saqib** [comment]
Thank you for resolving the issue! Does it require any installed libraries or packages to function?

**Comment by git-avc** [comment]
Just ODBC driver as required by ibis
https://ibis-project.org/backends/mssql

**Comment by nextchamp-saqib** [comment]
@git-avc 

Tried setting it up myself to see if it works. However, I found it to be quite complicated for a non-technical user, but there's nothing we can do about that.

Regarding the `driver` field in the data source, while moving it there does resolve the issue, it doesn't seem appropriate to keep it at the data source level since the drivers are actually configured at the server level. Therefore, I have relocated it to `common_site_config.json` and `site_config.json`

Thanks a lot for figuring things out!

**Comment by git-avc** [comment]
@nextchamp-saqib Great! 

> Tried setting it up myself to see if it works. However, I found it to be quite complicated for a non-technical user, but there's nothing we can do about that.

Since IBIS uses this kind of drivers, there are not other way. For direct connection I have used `pymssql` without driver requirement.

> Regarding the `driver` field in the data source, while moving it there does resolve the issue, it doesn't seem appropriate to keep it at the data source level since the drivers are actually configured at the server level. Therefore, I have relocated it to `common_site_config.json` and `site_config.json`
Absolutely agree.

Thanks!!!

**Pull request closed without merging**
