### PR TITLE
feat: Insights Copilot

### PR DESCRIPTION
**Pull request by nextchamp-saqib**
https://github.com/frappe/insights/assets/25369014/9a5e83ef-c3fc-4f46-93e7-e743ed25184c

---

Todo:
- [x] use openai function calls
- [x] find relevant tables based on the question
- [x] execute query if asked to
- [x] stream response using `frappe.publish_realtime`
- [ ] include only tables that have more recent and frequent data to reduce no. of tables in the schema
- [ ] Integrate Documentation in chat

### CODE REVIEW

**Comment by barredterra** [comment]
Nice work! What made you stop working on this?

> include only tables that have more recent and frequent data to reduce no. of tables in the schema

Maybe with newer models with a bigger context window, like `gpt-4-32k`, this will be less of an issue.

**Comment by barredterra** [comment]
Makes sense. Hopefully the accuracy will improve with newer models, bigger context and fine-tuning the prompt.

**Comment by aa-prashant** [comment]
@barredterra, isn't it about giving the model the local knowledge, Database tables their structure and meanings?

**Comment by nextchamp-saqib** [comment]
FYI:

Using `gpt-4` model which costs of avg `$0.02 / 1k tokens` the below generation consumed `$0.05` that's `₹4` per query 😅

Question: `find top 10 categories by order value`
Answer:
```sql
SELECT p.product_category_name, SUM(op.payment_value) AS total_order_value
FROM orderpayments op
JOIN orders o ON op.order_id = o.order_id
JOIN orderitems oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_category_name
ORDER BY total_order_value DESC
LIMIT 10
```

Using `gpt-3.5-turbo` which costs `$0.0013` on avg, consumed `$0.003` (`₹0.25` per query)

Question: `find top 10 categories by order value`
Answer:
```sql
SELECT product_category_name, SUM(price) as order_value
FROM orderitems
JOIN products ON orderitems.product_id = products.product_id
GROUP BY product_category_name
ORDER BY order_value DESC
LIMIT 10
```

**Comment by mhbu50** [comment]
@nextchamp-saqib Is this PR expected to be completed in the near future?
This is something we are so looking forward to

**Pull request closed without merging**
