### PR TITLE
feat: API data source

### PR DESCRIPTION
**Pull request by nextchamp-saqib**
Adds a new type of data source called `API`. This creates a local SQLite database to store request data. You can add requests under this source and on `sync` the `request data` is imported into SQLite database. The rest is handled by SQLite database connector

**API Data Source**

CleanShot 2023-04-04 at 21 08 12@2x

**API Data Source Request**

CleanShot 2023-04-04 at 21 08 29@2x

**Insights Table**

CleanShot 2023-04-04 at 21 08 48@2x

### CODE REVIEW

**Comment by blaggacao** [comment]
Would it be very complicated to expand this PR into adding a "webhook" data sources, so that for example https://github.com/ditdot-dev/vue-flow-form customer research can be fed to Insights?

**Comment by nextchamp-saqib** [comment]
Hi, @blaggacao
This PR is for the same. You will be able to make GET requests and fetch data from any endpoint.

**Comment by nextchamp-saqib** [comment]
> Would it be very complicated to expand this PR into adding a "webhook"/"endpoint" data source, so that for example https://github.com/ditdot-dev/vue-flow-form customer research can be fed to Insights?

Hey @blaggacao ,
The new script query (https://github.com/frappe/insights/pull/147) can be used to do this now

**Comment by nextchamp-saqib** [comment]
Script Query seems to be better and flexible alternative to this

**Pull request closed without merging**
